#!/bin/bash
# CSV to JSON converter using BASH
# Usage ./csv2json input.csv > output.json
 
input=$1
 
[ -z $1 ] && echo "No CSV input file specified" && exit 1
[ ! -s $input ] && echo "Could not find $input" && exit 1
 
read header_line < $input
header_line=$(echo -n $header_line|sed 's///')
a=0
headers=`echo $header_line | awk -F, {'print NF'}`
numlines=`cat $input | wc -l`
while [ $a -lt $headers ]
do
        head_array[$a]=$(echo $header_line | awk -v x=$(($a + 1)) -F"," '{print $x}')
        a=$(($a+1))
done
 
c=0
echo "["
while [ $c -lt $numlines ]
do
        read dataline
        # dataline=$(echo -n $dataline|sed 's///')
        if [ $c -ne 0 ]; then
                d=0
                echo "    {"
                IFS=',' read -r -a data_array <<< "$dataline"
                while [ $d -lt $headers ]
                do
                        val=${data_array[$d]}
                        # enclose in string if it's not a number
                        if ! [[ $val =~ ^[0-9]*.?[0-9]+$ ]]; then
                            val=\"$val\"
                        fi
                        echo -n "        "\"${head_array[$d]}\"": "$val
                        if [ $d -ne $(($headers-1)) ]; then
                            echo ","
                        else
                            echo
                        fi
                        d=$(($d+1))
                done
                if [ $c -eq $(($numlines-1)) ]; then
                        echo "    }"
                else
                        echo "    },"
                fi
        fi
        c=$(($c+1))
done < $input
echo "]"
